// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoyMSA4wXBov9oRFCeI8k5ADWET_SMmW8',
    appId: '1:886837437632:web:9fd77a1a560ed7e4e23925',
    messagingSenderId: '886837437632',
    projectId: 'to-do-app-1795b',
    authDomain: 'to-do-app-1795b.firebaseapp.com',
    databaseURL: 'https://to-do-app-1795b-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-app-1795b.appspot.com',
    measurementId: 'G-8JNVQV6G45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPTdWLyB7YgVhXxewij9UUJWfsaNd6MQ4',
    appId: '1:886837437632:android:9a9eda292ac22970e23925',
    messagingSenderId: '886837437632',
    projectId: 'to-do-app-1795b',
    databaseURL: 'https://to-do-app-1795b-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-app-1795b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5mqmd4vz2hx12RxCJ-zOodnDacWcefR0',
    appId: '1:886837437632:ios:3b8049c4f4e1459be23925',
    messagingSenderId: '886837437632',
    projectId: 'to-do-app-1795b',
    databaseURL: 'https://to-do-app-1795b-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-app-1795b.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAswZ023ZK49M9hWUL3admoAp7f9rZKjPw',
    appId: '1:10330954896:ios:1949e91253e37cfba38c15',
    messagingSenderId: '10330954896',
    projectId: 'to-do-app-f5f15',
    storageBucket: 'to-do-app-f5f15.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoyMSA4wXBov9oRFCeI8k5ADWET_SMmW8',
    appId: '1:886837437632:web:a09ef75a65982b5de23925',
    messagingSenderId: '886837437632',
    projectId: 'to-do-app-1795b',
    authDomain: 'to-do-app-1795b.firebaseapp.com',
    databaseURL: 'https://to-do-app-1795b-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-app-1795b.appspot.com',
    measurementId: 'G-64ZSR5Z4DP',
  );

}